print("Hello Prakhar! Welcome to Python Prakhar, all the best")
print("i wish you the success")
print("My life is wrecked")
print("I am not happy with my life")
print("I want to become a Cloud AI Engineer ")